# Generated by Django 4.0.2 on 2022-02-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
